// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_buy_all_the_hats = ""; // <GPGSID>
        public const string achievement_collect_100_fish = ""; // <GPGSID>
        public const string achievement_joining_the_ladder = ""; // <GPGSID>
        public const string achievement_collect_10_fish = ""; // <GPGSID>
        public const string achievement_collect_300_fish = ""; // <GPGSID>
        public const string achievement_money_in_the_bank = ""; // <GPGSID>
        public const string leaderboard_top_score = ""; // <GPGSID>
        public const string achievement_5_digits = ""; // <GPGSID>
        public const string achievement_classy = ""; // <GPGSID>
        public const string achievement_collect_25_fish = ""; // <GPGSID>
        public const string achievement_collect_50_fish = ""; // <GPGSID>
        public const string achievement_collect_75_fish = ""; // <GPGSID>

}

